# Basic
title: Tim's Blog
author: TimZeng
description: 嗨，我是王立明，一名来自黑龙江省鹤岗市的男生。<br/>现于无线生活（北京），从事互联网开发工作。

url: "https://wnglmng.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo: zengtian006
    github: zengtian006
    gplus: 112547382138552250597
    mail: zengtian006@gmail.com
