# Basic
title: Tim's Blog
author: TimZeng
description: Hi I'm Tim.

url: "https://zengtian006.github.io/"

permalink: /:year/:month/:title/

# Format
rouge: plain
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo: zengtian006
    github: zengtian006
    gplus: 112547382138552250597
    mail: zengtian006@gmail.com
